twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        images_directory: '%kernel.project_dir%\public\uploads\images'
        files_directory: '%kernel.project_dir%\public\uploads\files'
